
import { AbstractEmitter } from "./abstract";

export class ConcreteEmitter extends AbstractEmitter {
    // Keep this in line with the groups in /levels.ts
    identifiers = `!#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ`;


    output(obj: any): string {
        return this.outputHeader() + `
namespace level {

    /**
     * Custom block generated by the editor extension
     */
    //% weight=100
    //% blockId="custom_extension_block" block="custom extension block"
    export function customMethod() {
        // TODO: add implementation
    }

}`;
    }
}