export const CHANGE_IMAGE_TOOL = "CHANGE_IMAGE_TOOL";
export const CHANGE_CURSOR_SIZE = "CHANGE_CURSOR_SIZE";
export const CHANGE_SELECTED_COLOR = "CHANGE_SELECTED_COLOR";
export const CHANGE_IMAGE_DIMENSIONS = "CHANGE_IMAGE_DIMENSIONS";
export const CHANGE_KEY_MODIFIERS = "CHANGE_KEY_MODIFIERS";
export const CHANGE_CURSOR_LOCATION = "CHANGE_CURSOR_LOCATION";

export const IMAGE_EDIT = "IMAGE_EDIT";
export const UNDO_IMAGE_EDIT = "UNDO_IMAGE_EDIT";
export const REDO_IMAGE_EDIT = "REDO_IMAGE_EDIT";

export const TOGGLE_ASPECT_RATIO = "TOGGLE_ASPECT_RATIO";